#ifndef _RENDER_FONT_H_
#define _RENDER_FONT_H_

#include <stdint.h>
#include <volk/volk.h>
#include "mb/mb_str.h"

int font_test(void);

typedef uint8_t GlyphType;

/// Generated by chatgpt. Going to see where I can trim later on.
typedef struct GlyphInformation {
  GlyphType type;
  float u0, v0, u1, v1;

  int width, height;
  int bearing_x, bearing_y;

  int advance_x;
} GlyphInformation;

typedef struct FontTextureAtlas {
  VkImage image;
  int width, height;

  // both should be 1
  int pen_x, pen_y;
  int row_h;
  GlyphInformation information;
} FontTextureAtlas;

FontTextureAtlas font_load_into_texture_atlas(mb_StringView file_name);

#endif //  _RENDER_FONT_H_
